apiVersion: v1
kind: Pod
metadata: 
  name: data-pod
spec:
  containers:
    - name: database-container
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootroot"
        - name: MYSQL_DATABASE
          value: "mysqldemopod"
        - name: MYSQL_USER
          value: "raja"
        - name: MYSQL_PASSWORD
          value: "root@234"
  