
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec: 
  containers:
    - name: main-container
      image: nginx
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx 
    - name: sidecar-container
      image: bussybox
      args: ["bin/sh"]
      command: ["-c","tail -f  /var/log/nginx/error.log"]
      volumeMounts:
        - mountPath: /var/log/nginx
          name: nginx-logs

  volumes:
    - name: nginx-logs
      emptyDir: {}
          
